### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'models/seed4/csu/sesn0/lr0.m'

### ISSUE THREAD

**Issue by LatteWithoutSugar** [JC-Journal-Club/FOIT#1]
Excuse me, is the code missing files? What files are in the ’models’ folder?

**Comment by VoiceBeer** [comment]
Hi @Sensenf ! Sry for the trouble, I'll upload the models ASAP, and with that u'll get the results.

Also, in case you haven't divided the dataset (I divided both SEED and SEED-IV into three folders according to the sessions), I will update the specific file structure in the README. As for the data, please go to the [BCMI website](https://bcmi.sjtu.edu.cn/~seed/index.html) to apply for downloading the corresponding datasets (SEED and SEED-IV).
