### ISSUE TITLE
question

### ISSUE THREAD

**Issue by id8882222** [JC-Journal-Club/FOIT#2]
您好，在您的代码中用分类器对ud数据测试的结果来作为后续分类器的权重，这样是否会造成数据泄露呢？
![image](https://github.com/JC-Journal-Club/FOIT/assets/60727407/f5130cba-06e6-4866-b96f-7b4b2feae4f3)
![image](https://github.com/JC-Journal-Club/FOIT/assets/60727407/27c0c632-8142-464d-8b4a-71c38ce2f44e)

**Comment by id8882222** [comment]
另外，将accs打印出来，总有一个accs[i]等于1
![image](https://github.com/JC-Journal-Club/FOIT/assets/60727407/1e1e0de4-23f7-449c-b8de-cbd760bc2360)
![image](https://github.com/JC-Journal-Club/FOIT/assets/60727407/371bf12a-ef2f-43ee-9ea8-16caf7f043f9)

**Comment by VoiceBeer** [comment]
Hi，感谢您的提问。
抱歉这个代码我已经忘记当初写的时候的想法了现在尽量回答

关于问题1：我检查了下论文图和代码逻辑，您说的这部分应该是对的，按理来说B这一步测试的应该是calibration data也就是cd而不是ud。
问题2: 由于问题1导致这里确实有可能存在在ud上过拟合的分类器所以1.0的出现也正常。

总之抱歉代码错误造成的混淆，您可以尝试改一下B这一步的代码然后测试下提交一个PR。非常感谢您的关注！xD

祝好
